services:
  #PHP SERVICE
  php:
      build: 
          context: .
          target: php
          args: 
            - APP_ENV=${APP_ENV}
      environment:
        - APP_ENV=${APP_ENV}
        - CONTAINER_ROLE=app
      working_dir: /var/www
      volumes:
        - ./:/var/www
      ports:
        - 8000:8000
      depends_on:
        - database
        - redis
      

  #DATABASE SERVER
  database:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:  
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"  # Required for initialization
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

    #Redis Server
  redis:
      image: redis:alpine
      command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
      ports:
          - 6379:6379
volumes:
  db-data: ~
